apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapx-config
  namespace: fiapx
data:
  PORT: "8080"
  S3_ENDPOINT: "minio:9000"
  S3_BUCKET: "fiapx-videos"
  S3_USE_SSL: "false"
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
  SMTP_FROM: "notifications@fiapx.com"
  STORAGE_DRIVER: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: fiapx-secrets
  namespace: fiapx
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgrespassword@postgres:5432/fiapx_videos?sslmode=disable"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
  JWT_SECRET: "fiapx-hackathon-fase5-k8s-jwt-secret-key-2026"
